GARNAME = IO
GARVERSION = 1.25
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/IO-1.25.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/

LIBDEPS = apps/base/perl

DESCRIPTION =  load various IO modules
AUTHOR =  Graham Barr
URL = http://search.cpan.org/~gbarr/IO-1.25/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

