GARNAME = SQL-Statement
GARVERSION = 1.09
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/J/JZ/JZUCKER/ http://www.cpan.org/authors/id/J/JZ/JZUCKER/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/J/JZ/JZUCKER/

LIBDEPS = apps/base/perl

DESCRIPTION = Small SQL parser and engine

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

