GARNAME = MIME-tools
GARVERSION = 5.428
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

CPAN_AUTHOR_ID=/D/DS/DSKOLL/

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DO/DONEILL/

LIBDEPS = apps/perl/IO-Stringy apps/perl/MailTools

DESCRIPTION =  Parses streams to create MIME entities
AUTHOR = David F. Skoll 
URL = http://cpan.uwinnipeg.ca/~dskoll
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS =$(WORKSRC)/Makefile
TEST_SCRIPTS =$(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

