GARNAME = Cache-Cache
GARVERSION = 1.03
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/D/DC/DCLINTON/ http://www.cpan.org/authors/id/D/DC/DCLINTON/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/D/DC/DCLINTON/

LIBDEPS = apps/base/Error

DESCRIPTION = Generic cache interface and implementations

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

