GARNAME = XML-Parser-EasyTree
GARVERSION = 0.01
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/E/EB/EBOHLMAN/ http://www.cpan.org/authors/id/E/EB/EBOHLMAN/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/E/EB/EBOHLMAN/

LIBDEPS = apps/base/perl

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

