GARNAME = Sub-Exporter
GARVERSION = 0.984
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Sub-Exporter-0.984.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/

LIBDEPS = apps/perl/Data-OptList

DESCRIPTION = a sophisticated exporter for custom-built routines  
AUTHOR = Ricardo SIGNES
URL = http://search.cpan.org/~rjbs/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

