GARNAME = Class-ErrorHandler
GARVERSION = 0.02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#MASTER_SITES = http://www.cpan.org/authors/id/B/BT/BTROTT/ $(CPAN_MIRROR)/authors/id/B/BT/BTROTT/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/B/BT/BTROTT/
#MASTER_SITES = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/
MASTER_SITES = http://pkgs.fedoraproject.org/lookaside/pkgs/perl-Class-ErrorHandler/Class-ErrorHandler-0.02.tar.gz/b516490ce7cf919d690f40f68c59a37c/

LIBDEPS = apps/perl/perl

DESCRIPTION = Base class for error handling
AUTHOR = Benjamin Trott
URL = http://cpan.uwinnipeg.ca/~btrott
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

