--- work/bzip2-1.0.5/Makefile.old	2008-02-14 13:39:18.000000000 +0100
+++ work/bzip2-1.0.5/Makefile	2010-06-23 21:28:31.000000000 +0200
@@ -20,8 +20,8 @@
 RANLIB=ranlib
 LDFLAGS=
 
-BIGFILES=-D_FILE_OFFSET_BITS=64
-CFLAGS=-Wall -Winline -O2 -g $(BIGFILES)
+BIGFILES= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 
+CFLAGS=  -fPIC -Wall -Winline -O2 -g $(BIGFILES)
 
 # Where you want it installed when you do 'make install'
 PREFIX=/usr/local
@@ -70,6 +70,7 @@
 	@cat words3
 
 install: bzip2 bzip2recover
+	echo $(PREFIX)
 	if ( test ! -d $(PREFIX)/bin ) ; then mkdir -p $(PREFIX)/bin ; fi
 	if ( test ! -d $(PREFIX)/lib ) ; then mkdir -p $(PREFIX)/lib ; fi
 	if ( test ! -d $(PREFIX)/man ) ; then mkdir -p $(PREFIX)/man ; fi
