--- work/MonaLisa.v1.9/Makefile.new	1970-01-01 01:00:00.000000000 +0100
+++ work/MonaLisa.v1.9/Makefile	2007-03-21 13:23:27.000000000 +0100
@@ -0,0 +1,30 @@
+build:
+	tar zxvf $(DISTNAME).tar.gz
+	sed -i -e 's/`id /`env LD_LIBRARY_PATH= id /' MonaLisa.v1.9/Service/CMD/ML_SER
+ifneq ($(shell uname -s),Darwin)
+	$(PREFIX)/bin/perl ../../files/get_java.pl $(JAVA_PLATFORM) $(JAVA_VERSION) $(MASTER_SITES) && \
+	(cd $(DISTNAME) &&  \
+	JAVA_BIN=`ls ../j*.bin` && \
+	echo "yes" | sh $$JAVA_BIN | tee /dev/null && \
+	JAVA_HOME=j* && ln -sf $$JAVA_HOME java && cd $$JAVA_HOME ; \
+	rm -rf demo man sample src.zip jre/plugin jre/javaws)
+else
+	echo Java is already installed on Darwin
+endif
+	(cd $(DISTNAME)/Service/lib && \
+	for site in $(MASTER_SITES) ; do \
+	    env LD_LIBRARY_PATH= DYLD_LIBRARY_PATH=  PATH=/sw/bin:/sw/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin curl --fail $${site}../fdt/fdt.jar -o fdt.jar && break ; \
+	done ; test -s fdt.jar)
+
+install:
+	rm -rf $(PREFIX)/$(DISTNAME) ; rm -f $(PREFIX)/MonaLisa ; \
+	mkdir -p $(PREFIX); \
+	find $(DISTNAME) -exec touch {} \; ; \
+	cp -r $(DISTNAME) $(PREFIX)/ ; \
+	echo "Copying AliEn specific files..." ; \
+	mkdir -p $(PREFIX)/$(DISTNAME); \
+	cp install.sh install2.sh $(PREFIX)/$(DISTNAME)/; \
+	(cd ../../files ; \
+	find bin AliEn Control Service ! -path \*/CVS* -type d -exec mkdir -p $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find bin AliEn Control Service ! -path \*/CVS* -type f -exec cp {} $(PREFIX)/$(DISTNAME)/{} \; ) ; \
+	cd $(PREFIX)/ ; ln -sf $(DISTNAME) MonaLisa ; chmod -R a+r MonaLisa ; \
+	cd MonaLisa/bin ; chmod a+rx update_scripts.sh ; \
+	cd ../Service/CMD/ ; chmod a+rx common.sh CHECK_UPDATE ML_SER cmd_run.sh
