GARNAME = Array-Compare
GARVERSION = 2.01
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DA/DAVECROSS/

LIBDEPS = apps/base/perl

DESCRIPTION = Perl extension for comparing arrays. 
AUTHOR = Dave Cross
URL = http://search.cpan.org/~davecross/
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

