GARNAME = XML-Simple
GARVERSION = 2.13
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/G/GR/GRANTM/ http://www.cpan.org/authors/id/G/GR/GRANTM/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/G/GR/GRANTM/

LIBDEPS = apps/base/perl

DESCRIPTION = Easy API to maintain XML (esp config files)

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

