--- work/MonaLisa.v1.2/Makefile	1970-01-01 01:00:00.000000000 +0100
+++ work/MonaLisa.v1.2/Makefile.new	2005-07-01 12:12:25.832463775 +0200
@@ -0,0 +1,21 @@
+build:
+	$(PREFIX)/bin/perl ../../files/get_java.pl $(JAVA_PLATFORM) && \
+	tar zxvf $(DISTNAME).tar.gz && \
+	(cd $(DISTNAME) ; \
+	JAVA_BIN=`ls ../j2sdk*.bin` ; \
+	echo "yes" | sh $$JAVA_BIN | tee /dev/null ; \
+	JAVA_HOME=j2sdk* ; ln -sf $$JAVA_HOME java ; cd $$JAVA_HOME ; \
+	rm -rf demo man src.zip jre/plugin jre/javaws)
+
+install:
+	rm -rf $(PREFIX)/$(DISTNAME) ; rm -f MonaLisa ; \
+	mkdir -p $(PREFIX); \
+	cp -r $(DISTNAME) $(PREFIX)/ ; \
+	echo "Copying AliEn specific files..." ; \
+	(cd ../../files ; \
+	find AliEn ! -path \*/CVS* -type d -exec mkdir -p $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find AliEn ! -path \*/CVS* -type f -exec cp {} $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find Service ! -path \*/CVS* -type d -exec mkdir -p $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find Service ! -path \*/CVS* -type f -exec cp {} $(PREFIX)/$(DISTNAME)/{} \; ) ; \
+	cd $(PREFIX)/ ; ln -sf $(DISTNAME) MonaLisa
+
