GARNAME = Data-Dumper
GARVERSION = 2.121
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/I/IL/ILYAM/ http://www.cpan.org/authors/id/I/IL/ILYAM/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/I/IL/ILYAM/

LIBDEPS = apps/base/perl

DESCRIPTION = Convert data structure into perl code

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

