GARNAME    = glite
GARVERSION = 1.0.8
CATEGORIES = apps-tools
DISTFILES  = $(GARNAME)-$(GARVERSION)_src.tar.gz

MASTER_SITES = 

LIBDEPS =

DESCRIPTION = Glite project files
URL = http://www.glite.org
LICENSE = EGEE

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_ENV = env PREFIX=$(PREFIX)

CONFIGURE_ARGS =

include ../category.mk

x:
	echo $(MASTER_SITES)
	echo $(DISTFILES)


