GARNAME = muc-jcr
GARVERSION = 0.6.0
CATEGORIES = apps-tools
DISTFILES  = $(GARNAME)-$(GARVERSION).tar.gz
 
MASTER_SITES = 

LIBDEPS = apps/server/jabberd apps/gui/glib

DESCRIPTION = The Jabber Component Runtime
URL = http://jabber.terrapin.com/JCR/
AUTHOR = Paul Curtis
LICENSE = GPL2

CONFIGURE_SCRIPTS = 
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk
