--- work/MonaLisa.v1.2/Makefile	1970-01-01 01:00:00.000000000 +0100
+++ work/MonaLisa.v1.2/Makefile.new	2005-06-14 19:23:32.962260820 +0200
@@ -0,0 +1,14 @@
+
+install:
+	tar zxvf $(DISTNAME).tar.gz ; \
+	rm -rf $(PREFIX)/$(DISTNAME) ; \
+	mv $(DISTNAME) $(PREFIX)/ ; \
+	echo "Copying AliEn specific files..." ; \
+	(cd ../../files ; \
+	find AliEn ! -path \*/CVS* -type d -exec mkdir -p $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find AliEn ! -path \*/CVS* -type f -exec cp {} $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find Service ! -path \*/CVS* -type d -exec mkdir -p $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find Service ! -path \*/CVS* -type f -exec cp {} $(PREFIX)/$(DISTNAME)/{} \; ) ; \
+	cd $(PREFIX)/ ; rm -f MonaLisa ; \
+	ln -sf $(DISTNAME) MonaLisa
+
