GARNAME = Term-ReadLine-Gnu
GARVERSION = 1.15
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/H/HA/HAYASHI/ http://www.cpan.org/authors/id/H/HA/HAYASHI/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/H/HA/HAYASHI/

LIBDEPS = apps/base/perl apps/base/readline

DESCRIPTION = GNU Readline XS library wrapper

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = 

BUILD_ARGS =  

include ../category.mk

