GARNAME = Class-Accessor-Lite
GARVERSION = 0.05
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/K/KA/KAZUHO/Class-Accessor-Lite-0.05.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/K/KA/KAZUHO/

LIBDEPS = apps/perl/perl

DESCRIPTION = a minimalistic variant of Class::Accessor
LICENSE = Perl
URL = http://search.cpan.org/~kazuho/
AUTHOR = Kazuho Oku

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

