GARNAME = Params-Util
GARVERSION = 1.01
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/Params-Util-1.01.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/

LIBDEPS = apps/base/Scalar-List-Utils

DESCRIPTION =  Simple, compact and correct param-checking functions
AUTHOR = Adam Kennedy
URL = http://search.cpan.org/~adamk/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
#TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

