GARNAME = Devel-Modlist
GARVERSION = 0.5
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/R/RJ/RJRAY/ http://www.cpan.org/authors/id/R/RJ/RJRAY/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/R/RJ/RJRAY/

LIBDEPS = apps/base/perl

DESCRIPTION = Collect module use information

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

