GARNAME = Sys-Proctitle
GARVERSION = 0.04
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/O/OP/OPI/

LIBDEPS = apps/perl/perl

DESCRIPTION = Set the proctitle
LICENSE = Perl
URL = http://search.cpan.org/~opi/
AUTHOR = Torsten Foertsch

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

