GARNAME = common-sense
GARVERSION = 3.5
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/ML/MLEHMANN/

LIBDEPS = apps/perl/perl 

DESCRIPTION = JSON-XS server
LICENSE = Perl
URL = http://search.cpan.org/~mlehmann/
AUTHOR = Mark Lehmann

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

