GARNAME = Archive-Zip-SimpleZip
GARVERSION = 0.009
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/P/PM/PMQS/

LIBDEPS = apps/perl/perl

DESCRIPTION = zip64 wrapper
AUTHOR = PMQS
URL = http://search.cpan.org/CPAN/authors/id/P/PM/PMQS/
LICENSE = The Perl 5 License (Artistic 1 & GPL 1)


CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

 
