GARNAME = Log-Agent-Rotate
GARVERSION = 0.104
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES =

MASTER_SITES = 

LIBDEPS = apps/base/Getargs-Long apps/base/Compress-Zlib apps/base/LockFile-Simple

DESCRIPTION = Logging Agent
AUTHOR = Mark Rogaski
URL = http://search.cpan.org/~mrogaski
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

