GARNAME = DateManip
GARVERSION = 5.44

CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/S/SB/SBECK/

LIBDEPS = apps/base/perl

DESCRIPTION = Date manipulation routines 
URL = http://search.cpan.org/~sbeck/
AUTHOR = Sullivan Beck 
LICENSE = Perl

AUTOTEST =

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

