GARNAME = File-CacheDir
GARVERSION = 1.27
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/E/EA/EARL/ http://www.cpan.org/authors/id/E/EA/EARL/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/E/EA/EARL/

LIBDEPS = apps/base/perl

DESCRIPTION = auto ttl-based file cleanup without a cron

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

