#!/bin/sh
#############################################################################
# apkg - a front-end script to autopackage for AliEn
#############################################################################
#
#
# SYNOPSIS
#
# DESCRIPTION
#
# AUTHOR:
# Predrag Buncic, e-mail: Predrag.Buncic@cern.ch
#
# CREATION DATE:
#C<
#############################################################################
VERSION=0.01
###########################################################################
Error()
###########################################################################
{
   echo "Error:" $*
   exit 1
}
###########################################################################
Install()
###########################################################################
{
  [ ! -f $PREFIX/bin/apkg ] && cp $0 $PREFIX/bin

  TOOLS="tar wget pkg-config"

  for cmd in $TOOLS
  do
    which $cmd > /dev/null || Error "Cannot find $cmd command."
  done

  AUTOPACKAGES=""

  [ ! -f $PREFIX/bin/package -o ! -z $FORCE ] && \
                              AUTOPACKAGES=$AUTOPACKAGES" autopackage"

  [ ! -f $PREFIX/bin/apg++ -o ! -z $FORCE ] && \
                              AUTOPACKAGES=$AUTOPACKAGES" autopackage-apbuild"

  LIBS="glib-2.0 gtk+"

  ld_path=$LD_LIBRARY_PATH

  for lib in $LIBS
  do
    libs=`pkg-config --libs-only-L $lib | sed -e 's/ \?\-L/:/g'` || Error "Cannot find $lib on your system." 
    ld_path=$ld_path$libs 
    [ "$MODE" = "" ] && MODE="gtkfe"
 done

  [ ! -f $PREFIX/bin/autopackage-frontend-gtk -o ! -z $FORCE ] && \
                              AUTOPACKAGES=$AUTOPACKAGES" autopackage-gtkfe"

  [ ! -f $PREFIX/bin/autopackage-manager-gtk -o ! -z $FORCE ]  && \
                              AUTOPACKAGES=$AUTOPACKAGES" autopackage-manager"

  DIRS="/usr/lib/qt3/lib"

  for dir in $DIRS
  do
    if [ -d $dir ]
    then 
      ld_path=$ld_path:$dir
      # AUTOPACKAGES=$AUTOPACKAGES" autopackage-qtfe"
      # [ "$MODE" = "" ] && MODE="qtfe"
    fi
  done

  [ "$MODE" = "" ] && MODE="ttyfe"

  ld_path=`echo $ld_path | sed -e 's/ *//g' -e 's/::/:/g' -e 's/^://'`

  mkdir -p $PREFIX || Error "Cannot create directory: $PREFIX"

  EXTRAPACKAGES=""

  [ ! -f $PREFIX/lib/libuau.a -o ! -z $FORCE ]  && \
                               EXTRAPACKAGES=$EXTRAPACKAGES" luau-0.1.9"
  [ ! -f $PREFIX/bin/curl -o ! -z $FORCE ]  && \
                               EXTRAPACKAGES=$EXTRAPACKAGES" curl-7.13.2"
  [ ! -f $PREFIX/lib/libhistory.a -o ! -z $FORCE ] && \
                               EXTRAPACKAGES=$EXTRAPACKAGES" readline-5.0"

  for name in $EXTRAPACKAGES
  do
    (cd $PREFIX; wget -q -O - ${URL}/${name}_${PLATFORM}.tar.bz2 | tar jxf -)
  done

  for name in $AUTOPACKAGES
  do
    (cd $PREFIX; wget -q -O - ${URL}/${name}-${AUTOPACKAGE_VERSION}_${PLATFORM}.tar.bz2 | tar jxf -)
  done

  export LD_LIBRARY_PATH=$PREFIX/lib:$ld_path:$LD_LIBRARY_PATH
  export PATH=$PREFIX/bin:$PATH

  tmpdir=`mktemp -d /tmp/dialog.XXXXXX`

  mkdir -p $tmpdir || Error "Cannot create directory: $tmpdir"

  for pkg in $*
  do
    (cd $tmpdir && wget -q ${AUTOURL}/alien-meta-$pkg-${ALIEN_VERSION}.${autoplatform}.package && sh alien-meta-$pkg-${ALIEN_VERSION}.${autoplatform}.package --$MODE) || Error "Could not install $pkg"
  done

  rm -rf $tmpdir

}

###########################################################################
URL="http://alien.cern.ch/cache/dist"
AUTOURL="http://alien.cern.ch/cache/packages"
CACHEURL="http://alien.cern.ch/cache"
ALIEN_VERSION=1
AUTOPACKAGE_VERSION=1.05
###########################################################################

for dir in /usr/share/libtool /usr/lib/rpm 
do
  if [ -f $dir/config.guess ]
  then
    p=`$dir/config.guess`
    break
  fi
done

case $p in
  i*86-*-linux-gnu)
      platform=i686-pc-linux-gnu
      autoplatform=x86
      ;;
  x86_64-*-linux-gnu)
      platform=i686-pc-linux-gnu
      autoplatform=x86_64
      ;;
  powerpc-apple-darwin7.*)
      platform=powerpc-apple-darwin7.7.0
      autoplatform=ppc
      ;;
  ia64-*-linux-gnu)
      platform=ia64-unknown-linux-gnu
      autoplatform=ia64
      ;;
     *)
      Error "Unknown or unsupported platform: $platform"
      ;;
esac

PLATFORM=$platform
PREFIX="/opt/alien"
FORCE=""

args=$*
 
while [ $# -gt 0 ]
do
    case $1 in
        --platform)
            shift 1
	    PLATFORM=$1
            shift 1
           ;;
        --prefix)
            shift 1
	    PREFIX=$1
            shift 1
           ;;
        --url)
            shift 1
	    URL=$1
            shift 1
           ;;
        --autourl)
            shift 1
	    AUTOURL=$1
            shift 1
           ;;
        --trace)
            shift 1
	    set -vx
           ;;
        --force)
            shift 1
	    FORCE=true
           ;;
        -qt|--qtfe)
            shift 1
	    MODE=qtfe
           ;;
        -g|--gtkfe)
            shift 1
	    MODE=gtkfe
           ;;
        -t|--ttyfe)
            shift 1
	    MODE=ttyfe
           ;;
        install)
            shift 1
	    Install $*
            exit 
           ;;
        *)
           if [ -x $PREFIX/bin/package ] 
           then 
             $PREFIX/bin/package $*
             exit
           else
             Error "Unknown command: $*"
           fi
           ;;
    esac
done


