#!/bin/sh

mkdir -p autopackage

cat <<EOF>autopackage/skeleton.1
# -*- shell-script-mode -*-

[Meta]
RootName: @alien.cern.ch/$GARFNAME
DisplayName: $DESCRIPTION
ShortName: $GARNAME
Skeleton-Author: AntiDot
Skeleton-Version: 1
Repository: http://alien.cern.ch/cache/packages/$GARNAME.xml

[Notes]
Autogenerated skeleton.

[Test]
INTERFACE_VERSIONS=
SOFTWARE_VERSIONS=
#INTERFACE_VERSIONS=0.0.0
#SOFTWARE_VERSIONS="$INTERFACE_VERSIONS"

EOF

mkdir -p $PREFIX/share/autopackage/skeletons/@alien.cern.ch/$GARFNAME
mv autopackage/skeleton.1 $PREFIX/share/autopackage/skeletons/@alien.cern.ch/$GARFNAME

