GARNAME = Filesys-DiskSpace
GARVERSION = 0.05
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/F/FT/FTASSIN/ http://www.cpan.org/authors/id/F/FT/FTASSIN/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/F/FT/FTASSIN/

LIBDEPS = apps/base/perl

DESCRIPTION = Perl df (requires h2ph)

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

