GARNAME = SWIG
GARVERSION = 1.3.19
CATEGORIES = apps-tools
DISTFILES = swig-$(GARVERSION).tar.gz

MASTER_SITES = http://puzzle.dl.sourceforge.net/sourceforge/swig/ http://ovh.dl.sourceforge.net/sourceforge/swig/ http://alien.cern.ch/cache/

LIBDEPS = 

DESCRIPTION = SWIG
URL = http://www.swig.org/
AUTHOR = 
LICENSE = SWIG

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS) 

include ../category.mk
