GARNAME = HTML-Tagset
GARVERSION = 3.04
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/S/SB/SBURKE/ http://www.cpan.org/authors/id/S/SB/SBURKE/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/S/SB/SBURKE/

LIBDEPS = apps/base/perl

DESCRIPTION = data tables useful in parsing HTML

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

