GARNAME = Module-Signature
GARVERSION = 0.63
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/F/FL/FLORA/

LIBDEPS = apps/base/gnupg apps/base/Digest-SHA1

DESCRIPTION = Module signature file manipulation
AUTHOR = Autrijus Tang
URL = http://cpan.uwinnipeg.ca/~autrijus
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  
CONFIGURE_ENV = yes |  

include ../category.mk

