GARNAME = Data-OptList
GARVERSION = 0.107
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Data-OptList-0.107.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/

LIBDEPS = apps/perl/Params-Util

DESCRIPTION = parse and validate simple name/value option pairs  
AUTHOR = Ricardo SIGNES
URL = http://search.cpan.org/~rjbs/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

