GARNAME = expat
GARVERSION = 1.95.8
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://puzzle.dl.sourceforge.net/sourceforge/expat/ http://alien.cern.ch/cache/

LIBDEPS = 

DESCRIPTION = Expat XML Parser

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS) 

include ../category.mk
