GARNAME = Test-Requires
GARVERSION = 0.06
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/Test-Requires-0.06.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/ http://backpan.perl.org/authors/id/T/TO/TOKUHIROM/

LIBDEPS = apps/perl/perl

DESCRIPTION = Checks to see if the module can be loaded
LICENSE = Perl
URL = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/
AUTHOR = Tokuhirom

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

