GARNAME = Config-ApacheFormat
GARVERSION = 1.2
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/S/SA/SAMTREGAR/ http://www.cpan.org/authors/id/S/SA/SAMTREGAR/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/S/SA/SAMTREGAR/

LIBDEPS = apps/base/perl apps/base/Class-MethodMaker 

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

