GARNAME = Log-Dispatch-FileRotate
GARVERSION = 1.11
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/M/MA/MARKPF/ http://www.cpan.org/authors/id/M/MA/MARKPF/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/M/MA/MARKPF/

LIBDEPS = apps/base/perl apps/base/DateManip apps/base/Log-Dispatch apps/base/Log-Log4perl

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

