GARNAME = IO-Zlib
GARVERSION = 1.04
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/T/TO/TOMHUGHES/ http://www.cpan.org/authors/id/T/TO/TOMHUGHES/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/T/TO/TOMHUGHES/

LIBDEPS = apps/base/perl apps/base/Compress-Zlib

DESCRIPTION = IO:: style interface to Compress::Zlib

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

