GARNAME = Filesys-DiskFree
GARVERSION = 0.06
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/A/AB/ABARCLAY/ http://www.cpan.org/authors/id/A/AB/ABARCLAY/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/A/AB/ABARCLAY/

LIBDEPS = apps/base/perl

DESCRIPTION = OS independant parser of the df command

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

