GARNAME = eugridpma-carep
GARVERSION = 0.26
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
DISTNAME  = carep
BINDISTNAME = $(GARNAME)-$(GARVERSION)
PATCHFILES = Makefile.patch

MASTER_SITES = http://www.eugridpma.org/distribution/current/  http://alien.cern.ch/cache/

LIBDEPS = 

DESCRIPTION =  European Policy Management Authority for Grid Authentication in e-Science - acredited CA certificates


CONFIGURE_SCRIPTS =
BUILD_SCRIPTS =  
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = 
BUILD_ARGS   = 
INSTALL_ARGS = 

include ../category.mk

