
GARNAME = List-MoreUtils
GARVERSION = 0.33
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/


LIBDEPS = apps/perl/perl

AUTHOR  = ADAMK
LICENSE = Perl
URL     = http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/

DESCRIPTION =  Provide the stuff missing in List::Util  

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

