--- work/Linux-PAM-0.78/Makefile	Thu Oct 14 16:47:53 2004
+++ work/Linux-PAM-0.78/Makefile.new	Mon Feb 28 17:21:19 2005
@@ -13,7 +13,7 @@
 
 -include Make.Rules
 
-THINGSTOMAKE = libpam libpamc libpam_misc modules doc examples
+THINGSTOMAKE = libpam libpamc 
 
 all: $(THINGSTOMAKE)
 
--- work/Linux-PAM-0.78/defs/linux.defs	Wed Jun 21 00:10:46 2000
+++ work/Linux-PAM-0.78/defs/linux.defs.new	Mon Feb 28 17:36:41 2005
@@ -19,7 +19,7 @@
 LINKLIBS=-lc
 SOSWITCH=-soname
 NEEDSONAME=no
-LDCONFIG=/sbin/ldconfig
+LDCONFIG=echo
 AR=ar -cr
 RANLIB=ranlib
 FAKEROOT=
--- work/Linux-PAM-0.78/defs/redhat.defs	Wed Jun 21 00:10:46 2000
+++ work/Linux-PAM-0.78/defs/redhat.defs.new	Mon Feb 28 17:37:45 2005
@@ -22,7 +22,7 @@
 SOSWITCH=-soname
 LINKLIBS=-lc
 NEEDSONAME=no
-LDCONFIG=/sbin/ldconfig
+LDCONFIG=echo
 AR=ar -cr
 RANLIB=ranlib
 FAKEROOT=$(RPM_BUILD_ROOT)
--- work/Linux-PAM-0.78/configure.in	Wed Oct  6 16:04:34 2004
+++ work/Linux-PAM-0.78/configure.in.new	Mon Feb 28 17:42:09 2005
@@ -45,7 +45,7 @@
 USESONAME=yes			; AC_SUBST(USESONAME)
 SOSWITCH="-Wl,-soname -Wl,"	; AC_SUBST(SOSWITCH)
 NEEDSONAME=yes			; AC_SUBST(NEEDSONAME)
-LDCONFIG=/sbin/ldconfig		; AC_SUBST(LDCONFIG)
+LDCONFIG=echo			; AC_SUBST(LDCONFIG)
 
 dnl Checks for programs.
 AC_PROG_CC
