GARNAME = SOAP
GARVERSION = 0.28
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/K/KB/KBROWN/

LIBDEPS = apps/base/libwww-perl apps/base/XML-Parser

DESCRIPTION = Keith Brown
AUTHOR = 
URL = http://search.cpan.org/~kbrown/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =

AUTOTEST = 

CONFIGURE_ARGS = 

CONFIGURE_ENV = 

BUILD_ARGS =  

include ../category.mk

