GARNAME = Class-MethodMaker
GARVERSION = 2.18
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/S/SC/SCHWIGON/Class-MethodMaker-2.18.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/S/SC/SCHWIGON/

LIBDEPS = apps/perl/perl

DESCRIPTION = Create generic class methods
AUTHOR = Martyn J. Pearce
URL = http://cpan.uwinnipeg.ca/~fluffy
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

