GARNAME = libintl-perl
GARVERSION = 1.20
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/G/GU/GUIDO/ http://www.cpan.org/authors/id/G/GU/GUIDO/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/G/GU/GUIDO/

LIBDEPS = apps/base/perl

DESCRIPTION = Internationalization library for Perl
URL = http://search.cpan.org/~guido/
AUTHOR = Guido Flohr
LICENSE = Perl
 
CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile 

include ../category.mk

