GARNAME = Term-Cap
GARVERSION = 1.09
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/J/JS/JSTOWE/ http://www.cpan.org/authors/id/J/JS/JSTOWE/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/J/JS/JSTOWE/

LIBDEPS = apps/base/perl

DESCRIPTION = Basic termcap: Tgetent, Tputs, Tgoto

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

