GARNAME = Math-BigInt
GARVERSION = 1.74
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/T/TE/TELS/math/ http://www.cpan.org/authors/id/T/TE/TELS/math/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/T/TE/TELS/math/

LIBDEPS = apps/base/perl

DESCRIPTION = Arbitrary size integer math package

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

