GARNAME = Devel-StackTrace-AsHTML
GARVERSION = 0.11
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/Devel-StackTrace-AsHTML-0.11.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/ http://backpan.perl.org/authors/id/M/MI/MIYAGAWA/

LIBDEPS = apps/perl/Devel-StackTrace

DESCRIPTION = Displays stack trace in HTML  
LICENSE = Perl
URL = http://search.cpan.org/~miyagawa/
AUTHOR = Tatsuhiko Miyagawa

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

