GARNAME = Class-Inspector
GARVERSION = 1.27
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/Class-Inspector-1.27.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/

LIBDEPS = apps/perl/perl

DESCRIPTION = Get information about a class and its structure  
LICENSE = Perl
URL =  http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/
AUTHOR = Adam Kennedy

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

