GARNAME = libidn
GARVERSION = 0.5.9
CATEGORIES = libs
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = ftp://alpha.gnu.org/pub/gnu/libidn/ http://josefsson.org/libidn/releases/ http://alien.cern.ch/cache/

LIBDEPS = 

DESCRIPTION = GNU IDN Library
URL = http://www.gnu.org/software/libidn/
AUTHOR = 
LCIENSE = GPL2

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
