GARNAME = JSON
GARVERSION = 2.53
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MA/MAKAMAKA/

LIBDEPS = apps/perl/JSON-XS apps/perl/JSON-RPC

DESCRIPTION = JSON server
LICENSE = Perl
URL = http://search.cpan.org/~makamaka/
AUTHOR = Makamaka

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

