GARNAME = freetype
GARVERSION = 2.1.5
CATEGORIES = libs
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

LIBDEPS = 

MASTER_SITES = ftp://sunsite.cnlab-switch.ch/mirror/freetype/freetype2/ http://sunsite.cnlab-switch.ch/ftp/mirror/freetype/freetype2/ http://alien.cern.ch/cache/

DESCRIPTION = freetype2

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = 

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
