GARNAME = DBI
GARVERSION = 1.46
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/T/TI/TIMB/ http://www.cpan.org/authors/id/T/TI/TIMB/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/T/TI/TIMB/

LIBDEPS = apps/base/perl apps/base/PlRPC

DESCRIPTION = Generic Database Interface (see DBD modules)

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

