GARNAME = Test-Simple
GARVERSION = 1.001003
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/E/EX/EXODIST/

LIBDEPS = apps/perl/perl

DESCRIPTION = Basic utilities for writing tests.  
AUTHOR = EXODIST
URL = http://search.cpan.org/CPAN/authors/id/E/EX/EXODIST/
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

