GARNAME = XML-RegExp
GARVERSION = 0.03
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/T/TJ/TJMATHER/ http://www.cpan.org/authors/id/T/TJ/TJMATHER/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/T/TJ/TJMATHER/

LIBDEPS = apps/base/perl

DESCRIPTION = Regular expressions for XML tokens

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

