GARNAME = XML-Writer
GARVERSION = 0.520
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/J/JO/JOSEPHW/ http://www.cpan.org/authors/id/J/JO/JOSEPHW/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/J/JO/JOSEPHW/

LIBDEPS = apps/base/perl

DESCRIPTION = Module for writing XML documents

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

