GARNAME = BSD-Resource
GARVERSION = 1.24
CATEGORIES = apps-perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES =  http://search.cpan.org/CPAN/authors/id/J/JH/JHI/

LIBDEPS = apps/base/perl

DESCRIPTION = BSD process resource limit and priority functions 
AUTHOR = Jarkko Hietaniemi
URL = http://search.cpan.org/~jhi/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =
CONFIGURE_ENV  = 

include ../category.mk

