--- work/sloccount-2.26/makefile	2004-08-01 20:52:06.000000000 +0200
+++ work/sloccount-2.26/makefile.new	2005-07-01 17:27:43.562943151 +0200
@@ -28,7 +28,6 @@
 # Set this for where to store the man pages and executables.
 # If you want to store this as part of an official distribution,
 # change this to "/usr":
-PREFIX=/usr/local
 
 # Set "EXE_SUFFIX" to ".exe" if you're running on Windows, like this:
 # EXE_SUFFIX=.exe
