GARNAME = DateManip
GARVERSION = 5.42
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/S/SB/SBECK/ http://www.cpan.org/authors/id/S/SB/SBECK/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/S/SB/SBECK/

LIBDEPS = apps/base/perl

DESCRIPTION = Complete date/time manipulation package

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

