--- work/j2re1.4.2_08/Makefile	1970-01-01 01:00:00.000000000 +0100
+++ work/j2re1.4.2_08/Makefile.new	2005-05-19 13:54:46.444788763 +0200
@@ -0,0 +1,11 @@
+
+build:
+	cd .. ; \
+	echo yes | sh $(JAVA_BIN) | tee /dev/null
+
+install:
+	cd .. ; \
+	mkdir -p $(PREFIX) ; \
+	cp -r $(DISTNAME) $(PREFIX) ; rm $(PREFIX)/$(DISTNAME)/Makefile ; \
+	cd $(PREFIX) ; ln -sf $(DISTNAME) java
+
