GARNAME = Test-Exception
GARVERSION = 0.27
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AD/ADIE/

LIBDEPS = apps/base/Sub-Uplevel apps/base/Test-Simple

DESCRIPTION = Test exception based code 
AUTHOR = Adrian Howard
URL = http://search.cpan.org/~adie
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

