GARNAME = Devel-Trace
GARVERSION = 0.10
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/M/MJ/MJD/ http://www.cpan.org/authors/id/M/MJ/MJD/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/M/MJ/MJD/

LIBDEPS = apps/base/perl

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

TEST_ENV = printf "\n" |

BUILD_ARGS =  

include ../category.mk

