GARNAME = Types-Serialiser
GARVERSION = 1.0
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#ttp://search.cpan.org/CPAN/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.0.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/ML/MLEHMANN/

LIBDEPS = apps/perl/perl

DESCRIPTION = simple data types for common serialisation formats  
AUTHOR = Marc Lehmann 
URL = http://search.cpan.org/~mlehmann/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

