GARNAME = Error
GARVERSION = 0.15
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/U/UA/UARUN/ http://www.cpan.org/authors/id/U/UA/UARUN/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/U/UA/UARUN/

LIBDEPS = apps/base/perl

DESCRIPTION = Error/exception handling in an OO-ish way

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

