GARNAME = IO-Tty
GARVERSION = 1.08

CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/R/RG/RGIERSIG/ http://www.cpan.org/authors/id/R/RG/RGIERSIG/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/R/RG/RGIERSIG/

LIBDEPS = apps/base/perl
AUTHOR = Roland Giersig
URL = http://cpan.uwinnipeg.ca/~rgiersig
LICENSE = Perl

DESCRIPTION = provide an interface to TTYs and PTYs

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

