GARNAME = Tree-DAG_Node
GARVERSION = 1.22
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tgz
PATCHFILES = 
#http://search.cpan.org/CPAN/authors/id/R/RS/RSAVAGE/Tree-DAG_Node-1.11.tgz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RS/RSAVAGE/

LIBDEPS = apps/perl/perl

DESCRIPTION = Class for representing nodes in a tree 
AUTHOR = David Hand
URL = http://search.cpan.org/~cogent/
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

