GARNAME = eugridpma-carep
GARVERSION = 0.32
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
DISTNAME  = carep
BINDISTNAME = $(GARNAME)-$(GARVERSION)
PATCHFILES = Makefile.patch

MASTER_SITES =

LIBDEPS = 

DESCRIPTION =  European Policy Management Authority for Grid Authentication in e-Science - acredited CA certificates
LICENSE =
AUTHOR =
URL = http://www.eugridpma.org
 

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS =  
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = 
BUILD_ARGS   = 
INSTALL_ARGS = 

include ../category.mk

