--- work/openca-0.9.3-rc1/src/ext-modules/Makefile.old	2010-01-20 20:39:17.000000000 +0100
+++ work/openca-0.9.3-rc1/src/ext-modules/Makefile	2010-01-20 20:40:47.000000000 +0100
@@ -5,27 +5,27 @@
 TOP	= ../..
 include $(TOP)/Makefile.global-vars
 
-MODULES.pm.3rd-party	= \
-	Authen-SASL-2.04	\
-	CGI-Session-3.95	\
-	MIME-Base64-2.20	\
-	Convert-ASN1-0.18 	\
-	Digest-HMAC-1.01	\
-	Digest-MD5-2.24 	\
-	Digest-SHA1-2.02	\
-	libintl-perl-1.16	\
-	IO-Socket-SSL-1.01	\
-	IO-stringy-2.108	\
-	MIME-Lite-3.01		\
-	MIME-tools-5.411	\
-	MailTools-1.58		\
-	Net-Server-0.86		\
-	URI-1.23		\
-	XML-Parser-2.34		\
-	perl-ldap-0.33		\
-	Parse-RecDescent-1.94	\
-	X500-DN-0.28		\
-	XML-Twig-3.09
+MODULES.pm.3rd-party	= 
+#	Authen-SASL-2.04	\
+#	CGI-Session-3.95	\
+#	MIME-Base64-2.20	\
+#	Convert-ASN1-0.18 	\
+#	Digest-HMAC-1.01	\
+#	Digest-MD5-2.24 	\
+#	Digest-SHA1-2.02	\
+#	libintl-perl-1.16	\
+#	IO-Socket-SSL-1.01	\
+#	IO-stringy-2.108	\
+#	MIME-Lite-3.01		\
+#	MIME-tools-5.411	\
+#	MailTools-1.58		\
+#	Net-Server-0.86		\
+#	URI-1.23		\
+#	XML-Parser-2.34		\
+#	perl-ldap-0.33		\
+#	Parse-RecDescent-1.94	\
+#	X500-DN-0.28		\
+#	XML-Twig-3.09
 
 MODULES	= \
 	$(MODULES.pm.3rd-party)
