GARNAME = Switch
GARVERSION = 2.17
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/C/CH/CHORNY/

LIBDEPS = apps/perl/perl

DESCRIPTION = switch  
AUTHOR = C. Horny
URL = http://search.cpan.org/CPAN/authors/id/C/CH/CHORNY/
LICENSE = PERL 5

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

