GARNAME = Parse-RecDescent
GARVERSION = 1.94
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/D/DC/DCONWAY/ http://www.cpan.org/authors/id/D/DC/DCONWAY/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/D/DC/DCONWAY/

LIBDEPS = apps/base/perl

DESCRIPTION = Recursive descent parser generator
AUTHOR = Damian Conway
URL = http://cpan.uwinnipeg.ca/~dconway
LICENSE = Perl 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

