GARNAME =Module-Versions-Report
GARVERSION = 1.06
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/J/JE/JESSE/

LIBDEPS = apps/base/perl

DESCRIPTION = report versions of all modules in memory
AUTHOR = Sean M. Burke
URL = http://cpan.uwinnipeg.ca/~sburke
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

