GARNAME = XML-DOM
GARVERSION = 1.43
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/T/TJ/TJMATHER/ http://www.cpan.org/authors/id/T/TJ/TJMATHER/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/T/TJ/TJMATHER/

LIBDEPS = apps/base/perl apps/base/libwww-perl apps/base/libxml-perl apps/base/XML-RegExp

DESCRIPTION = Implements Level 1 of W3's DOM

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

