GARNAME = Image-WorldMap
GARVERSION = 0.14
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/L/LB/LBROCARD/ http://www.cpan.org/authors/id/L/LB/LBROCARD/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/L/LB/LBROCARD/

LIBDEPS = apps/gui/Image-Imlib2

DESCRIPTION = Create graphical world maps of data
AUTHOR = Leon Brocard
URL = http://cpan.uwinnipeg.ca/~lbrocard
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = 

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

