diff --speed-large-files --minimal -Nru tmp/org.gridsite.core/src/Makefile work/org.gridsite.core/src/Makefile
--- tmp/org.gridsite.core/src/Makefile	2012-04-12 12:52:45.000000000 +0200
+++ work/org.gridsite.core/src/Makefile	2012-05-18 16:26:04.272494782 +0200
@@ -44,9 +44,7 @@
 export prefix=/usr/local
 endif
 
-ifndef libdir
 export libdir=lib
-endif
 
 ifndef httpd_name
 export httpd_name=httpd
@@ -89,7 +87,7 @@
 libgridsite.so.$(VERSION): grst_err.o grst_x509.o grst_gacl.o grst_xacml.o \
                            grst_http.o grst_asn1.o grst_htcp.o
 	gcc -shared -Wl,-soname,libgridsite.so.$(MINOR_VERSION) \
-         -o libgridsite.so.$(PATCH_VERSION) \
+         $(MYLDFLAGS) -o libgridsite.so.$(PATCH_VERSION) \
          grst_err.o grst_x509.o grst_gacl.o grst_xacml.o grst_http.o \
          grst_asn1.o grst_htcp.o -lcrypto $(XML2_LIBS)
 	ln -sf libgridsite.so.$(VERSION) libgridsite.so
@@ -442,8 +440,8 @@
 	ln -sf htcp $(prefix)/bin/htping
 	ln -sf htcp $(prefix)/bin/htfind
 	cp -f gsexec $(prefix)/sbin
-	cp -f mod_gridsite.so $(prefix)/$(libdir)/$(httpd_name)/modules
-
+	cp -f mod_gridsite.so $(prefix)/httpd/modules
+	
 install-lib:
 	mkdir -p $(prefix)/$(libdir)
 	cp -f  libgridsite.a $(prefix)/$(libdir)
