--- work/gridsite-1.5.8/src/Makefile.new        2007-11-08 16:59:52.000000000 +0100
+++ work/gridsite-1.5.8/src/Makefile    2008-11-26 15:37:23.000000000 +0100
@@ -382,7 +382,7 @@
        ln -sf htcp $(prefix)/bin/htping
        ln -sf htcp $(prefix)/bin/htfind
        cp -f gsexec $(prefix)/sbin
-       cp -f mod_gridsite.so $(prefix)/lib/httpd/modules
+       cp -f mod_gridsite.so $(prefix)/httpd/modules

 install-lib:
        mkdir -p $(prefix)/$(libdir)
        