GARNAME = Class-Accessor
GARVERSION = 0.34
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/K/KA/KASEI/Class-Accessor-0.34.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/K/KA/KASEI/

LIBDEPS = apps/perl/perl

DESCRIPTION = Automated accessor generation  
LICENSE = Perl
URL = http://search.cpan.org/~kasei/
AUTHOR = Marty Pauley

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

