GARNAME = XML-LibXML
GARVERSION = 1.63
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://cpan.uwinnipeg.ca/cpan/authors/id/P/PA/PAJAS/

LIBDEPS = apps/base/XML-LibXML-Common

DESCRIPTION = Interface to the libxml library
AUTHOR = Petr Pajas
URL = http://cpan.uwinnipeg.ca/~pajas
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

