GARNAME = freetype
GARVERSION = 2.1.5
CATEGORIES = libs
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

LIBDEPS = apps/gcc/gcc

MASTER_SITES = ftp://sunsite.cnlab-switch.ch/mirror/freetype/freetype2/ http://sunsite.cnlab-switch.ch/ftp/mirror/freetype/freetype2/ 

DESCRIPTION = freetype2
URL = http://www.freetype.org/
AUTHOR = 
LICENSE = FreeType or GPL 

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = 

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
