GARNAME = Module-Implementation
GARVERSION = 0.06
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Module-Implementation-0.06.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/
LIBDEPS = apps/perl/Module-Runtime

DESCRIPTION = Loads one of several alternate underlying implementations for a module
AUTHOR = Dave Rolsky
URL = http://search.cpan.org/~drolsky/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

