GARNAME = Mozilla-CA
GARVERSION = 20120309
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/A/AB/ABH/Mozilla-CA-20120309.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AB/ABH/

LIBDEPS = apps/perl/perl

DESCRIPTION = Mozilla's CA cert bundle in PEM format
URL =  http://search.cpan.org/CPAN/authors/id/A/AB/ABH/
AUTHOR = Ask Bjørn Hansen 
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

