GARNAME = Test-Output
GARVERSION = 1.03
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/

LIBDEPS = apps/perl/Sub-Exporter apps/perl/Capture-Tiny

DESCRIPTION = Test for output 
AUTHOR = BDFOY
URL = http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/
LICENSE = The Perl 5 License (Artistic 1 & GPL 1)


CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

 