GARNAME = Image-Imlib2
GARVERSION = 1.03
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/L/LB/LBROCARD/ http://www.cpan.org/authors/id/L/LB/LBROCARD/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/L/LB/LBROCARD/

LIBDEPS = apps/base/perl apps/gui/imlib2

DESCRIPTION = Create graphical world maps of data

CONFIGURE_SCRIPTS = $(WORKSRC)/Build.PL
BUILD_SCRIPTS = $(WORKSRC)/Build
INSTALL_SCRIPTS = $(WORKSRC)/Build

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

