GARNAME = Class-Hook
GARVERSION = 0.01
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/P/PD/PDENIS/ http://www.cpan.org/authors/id/P/PD/PDENIS/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/P/PD/PDENIS/

LIBDEPS = apps/base/perl

DESCRIPTION = Add hooks on methods from other classes
AUTHOR = Pierre Denis
URL = http://cpan.uwinnipeg.ca/~pdenis
LICENSE = GPL or Artistic

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

