GARNAME = Module-Runtime
GARVERSION = 0.013
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/Module-Runtime-0.013.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/

LIBDEPS = apps/perl/perl

DESCRIPTION = runtime module handling
AUTHOR = Andrew Main (Zefram) 
URL = http://search.cpan.org/~zefram/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

