GARNAME = pkgconfig
GARVERSION = 0.15.0
CATEGORIES = misc
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

MASTER_SITES = http://ftp.acc.umu.se/pub/GNOME/sources/pkgconfig/0.15/

DESCRIPTION = Returns metainformation about installed libraries
AUTHOR =  Havoc Pennington
LICENSE = GPL
URL = http://freshmeat.net/projects/pkgconfig/

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
