GARNAME = Time-HiRes
GARVERSION = 1.9715
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/J/JH/JHI/

LIBDEPS = apps/base/perl

DESCRIPTION = High resolution alarm, sleep, gettimeofday, interval timers  
AUTHOR = Jarkko Hietaniemi 
URL = http://search.cpan.org/~jhi/
LICENSE = Perl

AUTOTEST =

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

