GARNAME = Net-IP
GARVERSION = 1.25
CATEGORIES = apps-perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MA/MANU/

LIBDEPS = apps/base/perl

DESCRIPTION = Perl extension for manipulating IPv4/IPv6 addresses 
AUTHOR = Manuel Valente
URL = http://search.cpan.org/~manu/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

