GARNAME = Test-Warnings
GARVERSION = 0.016
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/

LIBDEPS = apps/perl/perl

DESCRIPTION = Test for warnings and the lack of them  
AUTHOR = ETHER
URL = http://cpansearch.perl.org/src/ETHER
LICENSE = The Perl 5 License (Artistic 1 & GPL 1)


CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

 