GARNAME = HTTP-Body
GARVERSION = 1.15
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/G/GE/GETTY/HTTP-Body-1.15.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/G/GE/GETTY/

LIBDEPS = apps/perl/HTTP-Message apps/perl/Test-Deep

DESCRIPTION = HTTP-Body
LICENSE = Perl
URL = http://search.cpan.org/~getty/
AUTHOR = Torsten Raudssus

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

