GARNAME = XML-LibXML-Common
GARVERSION = 0.13
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://cpan.uwinnipeg.ca/cpan/authors/id/P/PH/PHISH/

LIBDEPS = apps/base/perl apps/base/libxml2

DESCRIPTION = Routines and Constants common for XML-LibXML and XML-GDOME
AUTHOR = Christian Glahn
URL = http://cpan.uwinnipeg.ca/~phish
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

