GARNAME = Test-TCP
GARVERSION = 1.17
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/Test-TCP-1.17.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/

LIBDEPS = apps/perl/Test-SharedFork

DESCRIPTION = testing TCP program
LICENSE = Perl
URL = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/
AUTHOR = MATSUNO Tokuhiro

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

