GARNAME = XML-Writer-String
GARVERSION = 0.1
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/S/SO/SOLIVER/ http://www.cpan.org/authors/id/S/SO/SOLIVER/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/S/SO/SOLIVER/

LIBDEPS = apps/base/perl

DESCRIPTION = Module to capture output from XML::Writer
AUTHOR = Simon Oliver
URL = http://cpan.uwinnipeg.ca/~soliver
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

