GARNAME = Test-Fatal
GARVERSION = 0.006
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/

LIBDEPS = apps/perl/Try-Tiny

DESCRIPTION = incredibly simple helpers for testing code with exceptions  
URL = http://search.cpan.org/dist/Test-Fatal/
AUTHOR = Ricardo SIGNES
LICENSE = Perl		

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

