GARNAME = Capture-Tiny
GARVERSION = 0.24
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/

LIBDEPS = apps/perl/perl

DESCRIPTION = Capture STDOUT and STDERR from Perl, XS or external programs   
AUTHOR = DAGOLDEN
URL = http://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/
LICENSE = The Perl 5 License (Artistic 1 & GPL 1)


CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

 