GARNAME = IO-Socket-SSL
GARVERSION = 0.96
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/B/BE/BEHROOZI/ http://www.cpan.org/authors/id/B/BE/BEHROOZI/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/B/BE/BEHROOZI/

LIBDEPS = apps/base/perl apps/base/openssl apps/base/Net_SSLeay.pm

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

