GARNAME = Stream-Buffered
GARVERSION = 0.02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DO/DOY/

LIBDEPS = apps/perl/perl

DESCRIPTION = temporary buffer to save bytes  
AUTHOR = Jesse Luehrs
URL = http://search.cpan.org/~doy/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

