GARNAME = DateTime-Format-W3CDTF
GARVERSION = 0.04
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/K/KE/KELLAN/ http://www.cpan.org/authors/id/K/KE/KELLAN/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/K/KE/KELLAN/

LIBDEPS = apps/base/DateTime

DESCRIPTION = Parse and format W3CDTF datetime strings
AUTHOR = Kellan Elliott-Mccrea
URL = http://cpan.uwinnipeg.ca/~kellan
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

