GARNAME = Router-Simple
GARVERSION = 0.15
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/Router-Simple-0.09.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/

LIBDEPS = apps/perl/Class-Accessor

DESCRIPTION = simple HTTP router
LICENSE = Perl
URL = http://search.cpan.org/CPAN/authors/id/T/TO/TOKUHIROM/Router-Simple
AUTHOR = MATSUNO Tokuhiro

CONFIGURE_SCRIPTS = $(WORKSRC)/Build.PL
BUILD_SCRIPTS = $(WORKSRC)/Build
INSTALL_SCRIPTS = $(WORKSRC)/Build
TEST_SCRIPTS = $(WORKSRC)/Build

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

