GARNAME = Test-Warn
GARVERSION = 0.10
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/C/CH/CHORNY/

LIBDEPS = apps/base/perl

DESCRIPTION = Perl extension to test methods for warnings
AUTHOR = Alexandr Ciornii
URL = http://search.cpan.org/~chorny/
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

