--- work/classads-0.9.7/Makefile	Thu Oct 28 23:53:21 2004
+++ work/classads-0.9.7/Makefile.new	Tue Mar 15 17:33:41 2005
@@ -3,16 +3,17 @@
 # This include will redefine DESTDIR, if Makefile.config exists
 include Makefile.config
 
-LD_FLAGS = $(EXTRA_LD_FLAGS) -L. -l$(LIB_LINK_NAME)
+LD_FLAGS = $(EXTRA_LD_FLAGS) $(LIB_NAME)
+LIBCLASSAD=libclassad.$(GARLIBEXT)
 
-all:: $(LIB_NAME) classad_functional_tester classad_unit_tester classad_version cxi extra_tests test_xml sample
+all:: $(LIB_NAME) $(LIBCLASSAD) classad_functional_tester classad_unit_tester classad_version cxi extra_tests test_xml sample
 
 LIB_INSTALL = $(DESTDIR)/lib
 BIN_INSTALL = $(DESTDIR)/bin
-INCLUDE_INSTALL = $(DESTDIR)/include
+INCLUDE_INSTALL = $(DESTDIR)/include/classads
 
 CPlusPlus = g++
-C_PLUS_FLAGS = $(EXTRA_C_PLUS_FLAGS) -Wall -g -DCLASSAD_DISTRIBUTION 
+C_PLUS_FLAGS = $(EXTRA_C_PLUS_FLAGS) -fPIC -Wall -g -DCLASSAD_DISTRIBUTION 
 INST_C_PLUS_FLAGS = $(C_PLUS_FLAGS) -w
 NO_INST_C_PLUS_FLAGS = -fno-implicit-templates $(C_PLUS_FLAGS)
 PURIFY = purify -g++=yes -chain-length=35 $(CPlusPlus)
@@ -65,14 +66,17 @@
 shared: shared.C
 	$(CPlusPlus) -fPIC -shared -o libshared.so shared.C
 
-install:: $(LIB_NAME) classad_functional_tester classad_unit_tester classad_version
-	mkdir -p $(LIB_INSTALL)
+$(LIBCLASSAD): $(LIB_OBJ)
+	rm -f $(LIBCLASSAD)
+	$(CPlusPlus) $(GARSHARED) $(LIB_OBJ) -o $(LIBCLASSAD)
+
+
+install:: $(LIB_NAME) 
+	mkdir -p $(LIB_INSTALL) 
 	mkdir -p $(BIN_INSTALL)
 	mkdir -p $(INCLUDE_INSTALL)
+	cp $(LIBCLASSAD) $(LIB_INSTALL)
 	cp $(LIB_NAME)  $(LIB_INSTALL)
-	cp classad_functional_tester $(BIN_INSTALL)
-	cp classad_unit_tester $(BIN_INSTALL)
-	cp classad_version $(BIN_INSTALL)
 	cp $(HEADER_FILES) $(INCLUDE_INSTALL)
 
 clean: tidy
@@ -81,3 +85,7 @@
 tidy:
 	rm -f *.o *~ *.bak
 
+test:  classad_unit_tester classad_version extra_tests
+	./classad_version
+	./classad_unit_tester
+	./extra_tests
