GARNAME = Sub-Install
GARVERSION = 0.926
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Sub-Install-0.926.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/

LIBDEPS = apps/perl/perl

DESCRIPTION = install subroutines into packages easily
AUTHOR = Ricardo SIGNES
URL = http://search.cpan.org/~rjbs
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

