GARNAME = Getopt-Declare
GARVERSION = 1.11
CATEGORIES = apps-perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = usage.diff

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DC/DCONWAY/

LIBDEPS = apps/base/perl

DESCRIPTION = Declaratively Expressed Command-Line Arguments via Regular Expressions
AUTHOR = Damian Conway
URL = http://search.cpan.org/~dconway/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

