GARNAME = XML-SAX-Base
GARVERSION = 1.02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/K/KH/KHAMPTON/ http://www.cpan.org/authors/id/K/KH/KHAMPTON/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/K/KH/KHAMPTON/

LIBDEPS = apps/base/perl

DESCRIPTION = Base class SAX Drivers and Filters

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

