GARNAME = XML-Generator
GARVERSION = 0.99
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/B/BH/BHOLZMAN/ http://www.cpan.org/authors/id/B/BH/BHOLZMAN/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/B/BH/BHOLZMAN/

LIBDEPS = apps/base/perl

DESCRIPTION = Generates XML documents

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

