GARNAME = Glade-Perl
GARVERSION = 0.61
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/D/DM/DMUSGR/ http://www.cpan.org/authors/id/D/DM/DMUSGR/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/D/DM/DMUSGR/

LIBDEPS = apps/base/perl apps/base/XML-Parser apps/gui/Gtk-Perl apps/base/Unicode-String

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

