GARNAME = Crypt-CBC
GARVERSION = 2.12
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/L/LD/LDS/ http://www.cpan.org/authors/id/L/LD/LDS/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/L/LD/LDS/

LIBDEPS = apps/base/perl 

DESCRIPTION = Cipherblock chaining for Crypt::DES/IDEA
AUTHOR =   Lincoln D. Stein 
URL = http://cpan.uwinnipeg.ca/~lds
LICENSE = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

