--- work/org.gridsite.core/src/Makefile 2009-07-23 16:28:59.000000000 +0200
+++ work/org.gridsite.core/src/Makefile.new     2010-05-14 05:51:42.000000000 +0200
@@ -44,9 +44,7 @@
 export prefix=/usr/local
 endif

-ifndef libdir
 export libdir=lib
-endif

 ifndef MYCFLAGS
 export MYCFLAGS=-I. -I../interface -I/usr/include/httpd -I/usr/include/apache2 -I/usr/include/apr-0 -I/usr/include/apr-1 -I/usr/include/apr-1.0 -I/opt/glite/include -fPIC -DLINUX=2 -D_REENTRANT -D_LARGEFILE64_SOURCE $(HTTPD_FLAGS)
@@ -75,7 +73,7 @@
 libgridsite.so.$(VERSION): grst_err.o grst_x509.o grst_gacl.o grst_xacml.o \
                            grst_http.o grst_asn1.o grst_htcp.o
        gcc -shared -Wl,-soname,libgridsite.so.$(MINOR_VERSION) \
-         -o libgridsite.so.$(PATCH_VERSION) -lcrypto `xml2-config --libs` \
+         -o libgridsite.so.$(PATCH_VERSION) -lcrypto `xml2-config --libs` -L$(prefix)/lib \
          grst_err.o grst_x509.o grst_gacl.o grst_xacml.o grst_http.o \
          grst_asn1.o grst_htcp.o
        ln -sf libgridsite.so.$(VERSION) libgridsite.so
@@ -426,7 +424,7 @@
        ln -sf htcp $(prefix)/bin/htping
        ln -sf htcp $(prefix)/bin/htfind
        cp -f gsexec $(prefix)/sbin
-       cp -f mod_gridsite.so $(prefix)/$(libdir)/httpd/modules
+       cp -f mod_gridsite.so $(prefix)/httpd/modules

 install-lib:
        mkdir -p $(prefix)/$(libdir)