GARNAME = Class-Class
GARVERSION = 0.18
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/B/BI/BINKLEY/ http://www.cpan.org/authors/id/B/BI/BINKLEY/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/B/BI/BINKLEY/

LIBDEPS = apps/base/perl

DESCRIPTION = Adds data members to Perl packages 
AUTHOR = B. K. Oxley
URL = http://cpan.uwinnipeg.ca/~binkley
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

