GARNAME    = glite-data
GARVERSION = 1.2.9
CATEGORIES = apps-tools
DISTFILES  = $(GARNAME)-$(GARVERSION)_src.tar.gz

MASTER_SITES = 

LIBDEPS = apps/glite/glite

DESCRIPTION = Glite data subproject files
URL = http://www.glite.org
LICENSE = EGEE

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS = 
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_ENV = env PREFIX=$(PREFIX)

CONFIGURE_ARGS =

include ../category.mk
