GARNAME = Filter-Template
GARVERSION = 1.02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RC/RCAPUTO/

LIBDEPS  = apps/base/perl

DESCRIPTION = A source filter for inline code templates
AUTHOR = Rocco Caputo
URL = http://search.cpan.org/~rcaputo/
LICENSE = Perl and GPL

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =

CONFIGURE_ARGS =

include ../category.mk

