GARNAME = Hash-MultiValue
GARVERSION = 0.12
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/A/AR/ARISTOTLE/Hash-MultiValue-0.12.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AR/ARISTOTLE/

LIBDEPS = apps/perl/perl

DESCRIPTION = Store multiple values per key
LICENSE = Perl
URL = http://search.cpan.org/CPAN/authors/id/A/AR/ARISTOTLE
AUTHOR = Aristotle

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

