GARNAME = IO-HTML
GARVERSION = 0.04
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/C/CJ/CJM/IO-HTML-0.04.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/C/CJ/CJM/

LIBDEPS = apps/perl/perl

DESCRIPTION = Open an HTML file with automatic charset detection
AUTHOR = Christopher J. Madsen
URL = http://search.cpan.org/~cjm/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

