GARNAME = Data-Properties
GARVERSION = 0.02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES =  http://mirror.switch.ch/ftp/mirror/CPAN/authors/id/I/IX/IX/
LIBDEPS = apps/base/perl

DESCRIPTION = Persistent properties
URL = http://search.cpan.org/~ix/
AUTHOR = Brian Moseley 
LICENSE = Perl

AUTOTEST =

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

