GARNAME = MailTools
GARVERSION = 1.67
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/M/MA/MARKOV/ http://www.cpan.org/authors/id/M/MA/MARKOV/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/M/MA/MARKOV/

LIBDEPS = apps/base/perl

DESCRIPTION = Various Mail related modules
AUTHOR = Mark Overmeer
URL = http://cpan.uwinnipeg.ca/~markov
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

