GARNAME = osg-ca
GARVERSION = 1.15a
CATEGORIES = apps-tools
DISTFILES   = osg-certificates-$(GARVERSION).tar.gz
DISTNAME = certificates
PATCHFILES = Makefile.patch 

#http://software.grid.iu.edu/pacman/cadist/1.15a/osg-certificates-1.15a.tar.gz
MASTER_SITES = http://software.grid.iu.edu/pacman/cadist/1.15a/

LIBDEPS = 

DESCRIPTION =   Open Science Grid - acredited CA certificates

LICENSE =
AUTHOR =
URL = http://software.grid.iu.edu/pacman/cadist/ca-certs-version
 

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS = 
INSTALL_SCRIPTS =  $(WORKSRC)/Makefile

CONFIGURE_ARGS = 
BUILD_ARGS   = 
INSTALL_ARGS = 

#PRE_BUILD = (mv $(WORKSRC)/certificates/* $(WORKSRC)/$(DISTNAME))

include ../category.mk

