GARNAME = Perl-Tidy
GARVERSION = 20031021
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/S/SH/SHANCOCK/ http://www.cpan.org/authors/id/S/SH/SHANCOCK/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/S/SH/SHANCOCK/

LIBDEPS = apps/base/perl

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

