GARNAME = CGI_Imagemap
GARVERSION = 1.00
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/M/MI/MIKEH/ http://www.cpan.org/authors/id/M/MI/MIKEH/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/M/MI/MIKEH/

LIBDEPS = apps/base/perl

DESCRIPTION = Imagemap handling for specialized apps

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

