GARNAME = readline
GARVERSION = 5.0
CATEGORIES = apps-libs
DISTFILES  = $(GARNAME)-$(GARVERSION).tar.gz


MASTER_SITES =   http://alien.cern.ch/cache/ ftp://ftp.gnu.org/gnu/readline/

LIBDEPS = 

DESCRIPTION =  The GNU Readline library

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk

