GARNAME = IO-Tty
GARVERSION = 1.10
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/IO-Tty-1.10.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/

LIBDEPS = apps/perl/perl

AUTHOR = Roland Giersig
URL = http://cpan.uwinnipeg.ca/~rgiersig
LICENSE = Perl

DESCRIPTION = provide an interface to TTYs and PTYs

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

