GARNAME = WSDL-Generator
GARVERSION = 0.02
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/P/PD/PDENIS/ http://www.cpan.org/authors/id/P/PD/PDENIS/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/P/PD/PDENIS/

LIBDEPS = apps/base/perl apps/base/Class-Hook

DESCRIPTION = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

