#!/bin/sh

set -vx

while [ $# -gt 0 ]
do
    case $1 in
        --name)
            shift 1
            name=$1
            shift 1
           ;;
        --help|-help)
            printf "Usage: %5s add-pkg --name [string] \n" $0
           ;;
        *)
           shift 1
           ;;
    esac
done

[ "$name" = "" ] && exit

lynx -dump http://cpan.uwinnipeg.ca/module/$name > /tmp/$$

file=`cat /tmp/$$ | grep "15. http://cpan.uwinnipeg.ca" | awk '{print $2}'`
id=`echo $file | awk -F"/authors/id|$name" '{print $2}'`
abstract=`cat /tmp/$$ | grep "^   Abstract " | awk '{print $2}'`
version=`cat /tmp/$$ | grep "^   Version " | awk '{print $2}'`

cat <<EOF
GARNAME = $name
GARVERSION = $version
CATEGORIES = apps-tools
DISTFILES = \$(GARNAME)-\$(GARVERSION).tar.gz

CPAN_AUTHOR_ID=$id

MASTER_SITES =\$(CPAN_MIRROR)/authors/id/\$(CPAN_AUTHOR_ID) http://www.cpan.org/authors/id/\$(CPAN_AUTHOR_ID) ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/\$(CPAN_AUTHOR_ID) 

LIBDEPS = apps/perl/perl

DESCRIPTION = $abstract

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = \$(WORKSRC)/Makefile
INSTALL_SCRIPTS =\ $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk
EOF
