TARGET_LIBNAME=lib
export MACOSX_DEPLOYMENT_TARGET=10.6
unexport LD_PREBIND
export GARLIBEXT=dylib
export GARSHARED=-dynamic
export OWN_LDFLAGS += -dylib -undefined dynamic_lookup -single_module
export OWN_CXXLDFLAGS += -dynamiclib -undefined dynamic_lookup -single_module
export MASKED := \
apps/alien/classad= \
apps/gcc/gcc= \
apps/portal/httpd= \
apps/portal/gridsite= \
apps/portal/mod_macro= \
apps/portal/mod_perl= \
apps/system/kerberos= \
apps/system/zlib= \
apps/system/libxml2 = \
apps/devel/autoconf= \
apps/devel/automake= \
apps/devel/libtool= \
apps/devel/jdk= \
apps/system/openssl= \
apps/tools/aria2= \ 
