GARNAME = File-Slurp-Tiny
GARVERSION = 0.003
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/

LIBDEPS = apps/perl/perl

DESCRIPTION = A simple, sane and efficient file slurper
AUTHOR = LEONT
URL = http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk