GARNAME = libghttp
GARVERSION = 1.0.9
CATEGORIES = libs
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

LIBDEPS = 

MASTER_SITES = http://ftp.gnome.org/pub/GNOME/sources/libghttp/1.0/ http://alien.cern.ch/cache/

DESCRIPTION = Gnome HTTP Library

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
