GARNAME = libghttp
GARVERSION = 1.0.9
CATEGORIES = libs
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

LIBDEPS = apps/gcc/gcc

MASTER_SITES = http://ftp.gnome.org/pub/GNOME/sources/libghttp/1.0/ 

DESCRIPTION = Gnome HTTP Library
URL = http://www.gnome.org
AUTHOR = Gnome Project
LICENSE = GPL2

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
