GARNAME = IPC-Run
GARVERSION = 0.78
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/R/RB/RBS/ http://www.cpan.org/authors/id/R/RB/RBS/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/R/RB/RBS/

LIBDEPS = apps/base/perl

DESCRIPTION = Child procs w/ piping, redir and psuedo-ttys

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

